### PR TITLE
Add a selectable check and a new SectionTitle item type

### PR DESCRIPTION
**Pull request by hansl**
This should be fully backward compatible (by default MenuItem is selectable, same as before).

### CODE REVIEW

**Comment by hansl** [comment]
I also need a section separator (just a line), but that could be done by either having a `SectionTitle` with `--------` temporarily, and later a custom menu item which I will do in another PR.

**Comment by bugadani** [comment]
I like this idea, but I think the current impl can't be placed into menus that have navigation items that return anything other than `()`. With the selectable check, though, you should be able to implement the menuitem for yourself in your code until we can figure out a more generic solution (like, `impl<T, R: Default> MenuItem<R> for SectionTitle<T, R>` which still isn't ideal).

**Comment by hansl** [comment]
Alright, I just did 3 changes;

1. prevent infinite loop when there's no item selectable anymore (which can happen)
2. add back `R` and if the unselectable is selected it returns `Default::default()` (as suggested by your last comment)
3. reset the selection correctly when building from a menu state, in case it selects an unselectable item. Added to the save_state example too as a test.

PTAL

**Comment by hansl** [comment]
Fixing the test and adding more tests.

**Comment by bugadani** [comment]
Thanks for doing this!

**Pull request merged**
