### PR TITLE
Allow the selected item R value to be returned without interacting

### PR DESCRIPTION
**Pull request by hansl**
In my case, I need to show different UI outside the menu when selecting certain items. Unfortunately the label nor the marker can be used currently for this purpose, I need the return value (which is an enum with some index into an array).

This could also be used for managing the Details string, but I think that's out the scope of this PR.

### CODE REVIEW

**Comment by bugadani** [comment]
I'm thinking maybe an `on_selected(callback_with_value)` would be a more elegant solution but to be honest I am not sure about this feature creep :)

That you want to convert arbitrary values associated to different menu items to a single type is definitely something I would like to avoid.

Maybe if you could describe your use case in a bit more detail, it would help to come up with a somewhat more streamlined solution.

**Comment by bugadani** [comment]
Also maybe this is just the initial impression I have at 10 past 10PM. I'll sleep on this PR, maybe I'll see things differently tomorrow.

**Comment by bugadani** [comment]
What I'm thinking about:
 - maybe we could add a more general `value_of(idx)` in addition to this method
 - maybe we could add `menu.selected_item()` if we can do `&dyn Something`
 - maybe we could do callbacks like in my comment above
 - and probably many other possible solutions

I think I can see the motivation, but it's also possible to turn the value-changes into events (I usually have one enum variant per menu item and track state on the outside based on what's returned on interaction), and track the currently selected menu item through the menu state, so technically what you want is possible to implement already. Clunky, but possible.

**Comment by hansl** [comment]
> Clunky, but possible.

Yes this is what I'm trying to avoid here. I'm separating the concern; the menu deals with selection and internal state, and the application deals with behaviours. By having a callback I would also have to implement duplication of state; I'd need to keep state of selection, which the menu already knows and is concerned about.

This PR solves my current issues nicely while also being backward compatible. See the bottom of this comment for what I'd suggest as an alternative (albeit not backward compatible).

----
## Usage

For some context, here's a screenshot of the menu I'm building:

image

There's two behaviours I want to add; 1. only show `(x) Details` when an item with details is selected (in this case, the cores themselves, and not the actions), and when using a special input my InputAdapter returns a different enum value, with the return value properly set.

Another constraint this solves for me is to allow my InputAdapter to return the `R` value with a different enum. Basically my InputAdapter returns the following enum:

```rust
pub enum SdlMenuAction<R> {
    Select(R),
    ShowDetails(R),
    LeftPage,
    RightPage,
    KeyPress(Keycode),
    Back,
    ChangeSort,
}
```

With only `Interaction::Select` being able to return the selected option's `R` (because InputAdapter cannot return `R`), this is essentially impossible to implement. Even with the callback you're suggesting this would be messy. By allowing someone to copy the `R` (R is `Copy` already so this isn't expensive), both application and adapters can access it. There doesn't need to be any changes in internals to the menu. It could even be argued that you could remove the `InputAction::Select` and replace it with `InputAction::Return(selected_value)`.

----

As an alternative, I'd suggest a few changes to `MenuItem<R>` (and friends) that aren't backward compatible:

1. remove any details logic from the main library, and move handling details at the application level. It is a functional concern, not a library one. This would be the biggest change, but would simplify a lot of the logic. Maybe have a `DetailedNavigationItem` or something to facilitate it, but don't make it a mandatory trait member.
2. remove everything from `MenuItem` that's not behavioural; `title`, `details`, `value`. The thinking here is that `draw_styled`, `interact`, `selectable` and maybe `set_style` are the only things necessary to display the menu. Add `value() -> R` so that applications have access to the R value of an item.
3. allow a `on_select_change` callback so that applications can make the necessary logic, although this can be done by simply comparing selected indices/`R` values. Either way it's fine.

I don't know if that sounds too much. I think it could be done in stride of smaller PRs, and I'm willing to put some of the work.

**Comment by hansl** [comment]
BTW, I don't see any usage of `MenuItem<R>::value` and `MenuItem<R>::title` and `MenuItem<R>::details` outside of showing details. I highly suggest showing details in a separate view as it is mainly a functional concern and should be handled by the application. Like I said, we could move that logic into `NavigationItem` (or a separate type) to facilitate usage, but mainly transitioning to separate views should not be a concern of the menu itself IMO.

It would simplify everything neatly.

**Comment by bugadani** [comment]
Oh wow you gave me a lot of good stuff here, thanks for that!

I think you are spot on with the details, I'll see what remains if I strip them out. If the current it's title is accessible, it's really not a big deal to switch views on the outside.

For now I've merged this PR and I appreciate you working on (and with!) embedded-menu very much! I'm going to cut a release, and start digging.

PS I absolutely adore those separator lines!

**Comment by hansl** [comment]
Thanks @bugadani.

I can also do some follow-up as I want to move my current types into this library too at some point (I have a few goodies).

**Comment by bugadani** [comment]
What is very interesting is that I've always considered the R type as a hack - something that needs to bring the different menu items to a common denominator. I never consciously thought of it as something that actually *identifies* the selected menu item, even though I've been using it as such since forever.

However, this re-conceptualization changes a lot. It's possible to attach arbitrary application-specific data to menu items through their R values; essentially it becomes possible to attach a description text to the menu item even with the removal of the whole description concept.

One more thing it enables: we may be able to remove NavigationItem entirely. It's essentially a single-value Select. It wouldn't play nice with the Menu macro but as it turns out, it isn't as useful as I intended it to be anyway.

We may also remove SectionTitle by making the selectability user-configurable, though that might be stretching the idea a bit :)

**Pull request merged**
