### PR TITLE
Add a color invert as a selection indicator

### PR DESCRIPTION
**Pull request by hansl**
It seems a bug in interpolate was introduced, which makes single touch act weird. But since it happens to all other selectors I didn't think it was in my code.

### CODE REVIEW

**Comment by bugadani** [comment]
Do you mean the short jerkyness after it fills up? Yeah that might be on me.

**Comment by hansl** [comment]
Yes. Please don't merge this PR yet, there's an issue with it.

**Comment by bugadani** [comment]
So, after playing with this a bit I like the idea of an inverting indicator but I don't like how it looks. I think the fill should respect the top/bottom margins to not touch the text of the other items. Right now it looks weird if an item contains a `Q` (or other letters with descenders) as the inverting area seems to make assumptions on the margin maybe.

> Please don't merge

You can use the "convert to draft" option to actually take away my big green merge button while you're working on it :)

**Comment by hansl** [comment]
> Right now it looks weird if an item contains a Q (or other letters with descenders) as the inverting area seems to make assumptions on the margin maybe.

That's the issue I mentioned, I'm looking at it. It's how the text is displayed, seems like it's cropped. It's not a margin issue (if I play around with the margin it works as expected).

**Comment by hansl** [comment]
Margin top and bottom aren't used properly on the items themselves.

**Comment by hansl** [comment]
I ended up fixing only the calculation for the invert rectangle, but I think margin top/bottom should also be used _between_ items, and it's not. I looked quickly through the code but adding margins into the `draw_styled` call didn't fix it, so I gave up. This last commit fixes the issue with letters that have bottom pixels.

I think you have more knowledge of the code for this. It does affect how things are rendered, not just the indicator.

**Comment by bugadani** [comment]
I guess the problem is that I treated (at least in name) those insets as margin in one place and padding in another. I'll look into cleaning this up, but otherwise this looks good to go, thank you!

**Pull request merged**
